# Generated by Django 3.1.7 on 2021-08-15 20:59

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coin_name', models.CharField(max_length=50)),
                ('coin_image', models.ImageField(upload_to='pics')),
                ('wallet_address', models.CharField(max_length=16)),
                ('wallet_backcode', models.ImageField(upload_to='pics')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=20)),
                ('min_amount', models.IntegerField(default=0)),
                ('max_amount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_profile', serialize=False, to='auth.user')),
                ('ref_by', models.CharField(max_length=50)),
                ('address', models.CharField(blank=True, max_length=1024, null=True, verbose_name='Address ')),
                ('zip_code', models.CharField(blank=True, max_length=12, null=True)),
                ('country', django_countries.fields.CountryField(blank=True, max_length=2, null=True)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('deposit_wallet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('interest_wallet', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_coin', to='account.cryptodetails')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw', to='account.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('investment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False)),
                ('coin_deposit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invest_crypto', to='account.cryptodetails')),
                ('investment_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_plan', to='account.plan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_account', to='account.userprofile')),
            ],
        ),
    ]
